version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.1.3
    - 24.1.5
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.13.8
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.13.8
  - dependency-name: npm
    versions:
    - 6.14.10
    - 6.14.11
  - dependency-name: ini
    versions:
    - 1.3.7
  - dependency-name: vue-router
    versions:
    - 3.4.9
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: handlebars
    versions:
    - 4.7.6
